yarnPath: .yarn/releases/yarn-4.3.1.cjs

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
    - ia32
  os:
    - current
    - darwin
    - linux
    - win32

nodeLinker: node-modules